library:
\tgcc -c CLStringType.c -o CLStringType.o
\tgcc -c CLArrayType.c -o CLArrayType.o
\tgcc -c CLMutableArrayType.c -o CLMutableArrayType.o
\tgcc -c CLDictionaryType.c -o CLDictionaryType.o
\tgcc -c CLURLType.c -o CLURLType.o
\tgcc -c CLInternetRequest.c -o CLInternetRequest.o
\tgcc -o output CLStringType.o CLArrayType.o CLMutableArrayType.o CLDictionaryType.o CLURLType.o CLInternetRequest.o -lobjc
\tlibtool --mode=link gcc -g -O -o libclcore.a
