library:
	gcc -c CLStringType.c
	gcc -c CLArrayType.c
	gcc -c CLMutableArrayType.c
	gcc -c CLDictionaryType.c
	gcc -c CLURLType.c
	gcc -c CLInternetRequest.c
	gcc -shared -o libclcore.so CLStringType.o CLArrayType.o CLMutableArrayType.o CLDictionaryType.o CLURLType.o CLInternetRequest.o
	rm CLStringType.o CLArrayType.o CLMutableArrayType.o CLDictionaryType.o CLURLType.o CLInternetRequest.o
