library:
	gcc std=c99 -c CLStringType.c -o CLStringType.o
	gcc std=c99 -c CLArrayType.c -o CLArrayType.o
	gcc std=c99 -c CLMutableArrayType.c -o CLMutableArrayType.o
	gcc std=c99 -c CLDictionaryType.c -o CLDictionaryType.o
	gcc std=c99 -c CLURLType.c -o CLURLType.o
	gcc std=c99 -c CLInternetRequest.c -o CLInternetRequest.o
	gcc std=c99 -o output CLStringType.o CLArrayType.o CLMutableArrayType.o CLDictionaryType.o CLURLType.o CLInternetRequest.o -lobjc
	libtool --mode=link gcc std=c99 -g -O -o libclcore.a
